apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-api
  template:
    metadata:
      labels:
        app: insurance-api
    spec:
      containers:
        - name: insurance-api
          image: __IMAGE_NAME__  
          ports:
            - containerPort: 5000
