apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-app 
        image: sathwik2410/insurance-cost-predictor:latest

        ports:
        - containerPort: 5000
