apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app-deployment
  labels:
    app: mlops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
      - name: mlops-container
        image: __IMAGE_NAME__  
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"