apiVersion: v1
kind: Service
metadata:
  name: mlops-app-service
spec:
  type: LoadBalancer
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30036  