name: CI/CD - Build, Push, and Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push to Docker Hub

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: 4. Run Tests
        run: pytest

      - name: 5. Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 6. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 7. Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/insurance-predictor:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/insurance-predictor:${{ github.sha }}

      - name: 8. Save Docker Image Tag
        id: image_tag
        run: echo "IMAGE_TAG=${{ secrets.DOCKER_HUB_USERNAME }}/insurance-predictor:${{ github.sha }}" >> $GITHUB_ENV

  deploy-to-minikube:
    runs-on: ubuntu-latest
    name: Deploy to Minikube
    needs: build-and-push

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set Up and Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker

      - name: 3. Enable Ingress (optional)
        run: minikube addons enable ingress

      - name: 4. Set kubectl context to Minikube
        run: kubectl config use-context minikube

      - name: 5. Replace image placeholder in deployment.yaml
        run: |
          sed -i "s|__IMAGE_NAME__|${{ env.IMAGE_TAG }}|g" app/k8s/deployment.yaml

      - name: 6. Deploy to Kubernetes
        run: |
          kubectl apply -f app/k8s/deployment.yaml
          kubectl apply -f app/k8s/service.yaml

      - name: 7. Wait for Deployment Rollout
        run: |
          kubectl rollout status deployment/mlops-app-deployment --timeout=120s
          kubectl get pods
          kubectl get svc

      - name: 8. Get Minikube Service URL
        run: |
          minikube service mlops-app-service --url > service_url.txt
          cat service_url.txt

      - name: 9. Upload Minikube Service URL
        uses: actions/upload-artifact@v4
        with:
          name: minikube-service-url
          path: service_url.txt
