name: CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t insurance-api .
    - name: Run container
      run: docker run -d -p 5000:5000 insurance-api
