name: Retrain Model

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run retraining script
      run: python retrain.py

    - name: Push retrained model to repo
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add -A
        git commit -m "Retrained model"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Sathwik2410/Insurance_Cost_MLOps.git HEAD:main
